config/routes.rb
Rails.application.routes.draw do
  resources :user_stocks, only: [:create, :destroy]

  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
   root "home#index"
   get 'my_portfolio', to: 'users#my_portfolio'
   get 'search_stock', to: 'stocks#search'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/stock.rb
require 'httparty'

class Stock < ApplicationRecord
  has_many :user_stocks
  has_many :users, through: :user_stocks

  validates :name, :ticker, presence: true

  def self.new_lookup(symbol)
    return nil if symbol.blank?  # Check if the symbol is empty

    api_key = Rails.application.credentials.alpha_vantage_client[:api_key]
    response = HTTParty.get("https://www.alphavantage.co/query?function=GLOBAL_QUOTE&symbol=#{symbol}&apikey=#{api_key}")

    puts "Response Code: #{response.code}"
    puts "Response Body: #{response.body}"

    if response.code == 200 && response.parsed_response['Global Quote'].present?
      global_quote = response.parsed_response['Global Quote']
      price = global_quote['05. price']
      name = global_quote['01. symbol']

      # Check if the response contains valid data for a stock
      if price.present? && name.present?
        stock = new(ticker: symbol, name: name, last_price: price)

        # Check if the new record is valid
        if stock.valid?
          stock
        else
          nil
        end
      else
        nil  # Handle the case where the response does not contain valid stock data
      end
    else
      nil  # Handle the case where the API response is not successful or the "Global Quote" is empty
    end
  end
  def self.check_db(ticker_symbol)
    where(ticker: ticker_symbol).first
  end
end



# require 'httparty'

# class Stock < ApplicationRecord
#   def self.new_lookup(symbol)
#     api_key = Rails.application.credentials.alpha_vantage_client[:api_key]
#     response = HTTParty.get("https://www.alphavantage.co/query?function=GLOBAL_QUOTE&symbol=#{symbol}&apikey=Rails.application.credentials.alpha_vantage_client[:api_key]")

#     if response.code == 200 && response.parsed_response['Global Quote']
#         price = response.parsed_response['Global Quote']['05. price']
#         name = response.parsed_response['Global Quote']['01. symbol']
#        new(ticker: symbol, name: name, last_price: price)
#     else
#         nil
#     end
#   end
# end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_stocks
  has_many :stocks, through: :user_stocks

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def stock_already_tracked?(ticker_symbol)
    stock = Stock.check_db(ticker_symbol)
    return false unless stock
    stocks.where(id:stock.id).exists?
  end

  def under_stock_limit?
    stocks.count < 10
  end

  def can_track_stock?(ticker_symbol)
    puts "Ticker: #{ticker_symbol}"
    puts "Stock already tracked: #{stock_already_tracked?(ticker_symbol)}"
    under_stock_limit? && !stock_already_tracked?(ticker_symbol)
  end

end

app/models/user_stock.rb
class UserStock < ApplicationRecord
  belongs_to :user
  belongs_to :stock
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    
    def index 
        
    end
end

app/controllers/stocks_controller.rb
 class StocksController < ApplicationController

    def search
        if params[:stock].present?
            @stock = Stock.new_lookup(params[:stock])
            @tracked_stocks = current_user.stocks #need to define it so it doesn't upload as nil and crashes the app
            if @stock
              render 'users/my_portfolio'
            else
              flash[:alert] = "Please enter a valid symbol to search"
              redirect_to my_portfolio_path
            end


        else
            flash[:alert] = "Please enter a symbol to search"
            redirect_to my_portfolio_path
        end
    end

end

app/controllers/user_stocks_controller.rb
class UserStocksController < ApplicationController

  def create
    #need to create method to check if stock is in the database (in the controller, then call it here)!
    stock = Stock.check_db(params[:ticker])
    if stock.blank?
      stock = Stock.new_lookup(params[:ticker])
      stock.save
      @user_stock = UserStock.create(user:current_user, stock: stock)
      flash[:notice] = "Stock #{stock.name} was successfully added to your portfolio"
      redirect_to my_portfolio_path
    end
  end

  def destroy
    stock = Stock.find(params[:id])
    user_stock = UserStock.where(user_id: current_user.id, stock_id: stock.id).first
    user_stock.destroy
    flash[:notice]="#{stock.ticker} was successfully removed from your portfolio"
    redirect_to my_portfolio_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def my_portfolio
    @tracked_stocks = current_user.stocks
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_stocks_helper.rb
module UserStocksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<h1> Welcome to Stock Tracker</h1>
<p>Your Personal Finance Tracking Solution</p>
<p>Start managing your finances with ease. Track stock, analyze trends, and achieve your financial goals.</p>

<%# <%= link_to 'Sign Out', destroy_user_session_path, data: {turbo_method: :delete }  %> 

app/views/layouts/_messages.html.erb
<% flash.each do |name, message| %>
<div class="container">
<div class="alert alert-success alert-<%= name== 'notice' ? 'success' : 'danger' %> fade show" role="alert">
<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
<%= message %>
<% end %>
</div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container">
    <%= link_to root_path, class:"navbar-brand"  do %>
    <%= image_tag("logo.png", alt: "Stock Tracker Logo", width:"150", height:"150") %>
    <% end %>
    <% if current_user %>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <% link_style = (request.path == my_portfolio_path) ? 'nav-link active' : 'nav-link' %>
            <%= link_to 'My Portfolio', my_portfolio_path, class: link_style %>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false" data-turbo="false">
              Dropdown
            </a>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="#">Action</a></li>
              <li><a class="dropdown-item" href="#">Another action</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="#">Something else here</a></li>
            </ul>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" aria-disabled="true">Disabled</a>
          </li>
        </ul>

  <ul class="navbar-nav ml-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <%= link_to('Logout', destroy_user_session_path, class:"btn btn-sm btn-danger mx-2",  data: {turbo_method: :delete }) %>
          </li>
        </ul>

        <form class="d-flex" role="search">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
      </div>
      <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FinanceTracker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "custom", "data-turbo-track": "reload" %>
    <%= javascript_include_tag 'application', 'data-turbo-track': 'reload' %>
    <%= javascript_importmap_tags %>
</head>

  <body>
    <%= render 'layouts/navigation' %>
    <div class="container">
      <%= render 'layouts/messages' %>
      <div class="container">
        <%= yield %>
      </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
  
  </body>
  
</html>

app/views/stocks/_list.html.erb
<div class='row'>
  <div class='col-9'>
    <table class="table table-bordered table-hover mt-4">
      <thead>
        <tr>
          <th scope="col">Ticker</th>
          <th scope="col">Name</th>
          <th scope="col">Price</th>
          <th scope="col">Actions</th>
        </tr>
      </thead>
      <tbody>

      <% @tracked_stocks.each do |stock| %>
        <tr>
          <th scope="row"><%= stock.ticker %></th>
          <td><%= stock.name %></td>
          <td><%= stock.last_price %></td>
          <td><%= button_to 'Remove', user_stock_path(stock), method: :delete, data:{turbo_confirm: 'Are you sure?'}, class: 'btn btn-sm btn-warning' %></td>
        </tr>
      <% end %>

      </tbody>
    </table>
  </div>
</div>

app/views/users/_result.html.erb
<% if @stock %>
  <div class="mt-4 results-block">
    <strong>Symbol: </strong> <%= @stock.ticker %>
    <strong>Name: </strong> <%= @stock.name %>
    <strong>Price: </strong> <%= @stock.last_price %>
    
    <% if current_user.can_track_stock?(@stock.ticker) %>
      <%= button_to 'Add to Portfolio', user_stocks_path(user: current_user, ticker: @stock.ticker), 
      class: 'btn btn-sm btn-primary', method: :post %>
    <% else %>
      <span class="badge bg-secondary">
      You are already tracking

      <% if !current_user.under_stock_limit? %>
        10 stocks
      <% end %>

      <% if current_user.stock_already_tracked?(@stock.ticker) %>
        this stock
      <% end %>

    <% end %>
  </div>
<% end %>

app/views/users/my_portfolio.html.erb
<h1>My Portfolio</h1>

<div class="search-area">
  <h3>Search Stocks</h3>
  <%= form_tag search_stock_path, data: {turbo: false}, remote: true, method: :get do %>
    <div class="form-group row">
        <div class="col-sm-9 no-right-padding">
            <%= text_field_tag :stock, params[:stock], placeholder: "Stock ticker symbol", autofocus: true, class: "form-control form-control-lg" %>
        </div>
        <div class="col-sm-3 no-left-padding">
            <%= button_tag type: :submit, class: "btn btn-success", name:"search_button", value: "Search" do %>
              <%= fa_icon 'search 2x' %>
            <% end %>
        </div>
    </div>
  <% end %>
</div>

<div class='row'>
  <div class='col-9'>
<%= render 'users/result' %>
  </div>
</div>

<% if !@tracked_stocks.empty? %>
  <%= render 'stocks/list' %>
<% end %>